### ISSUE TITLE
Events for paper-menu or paper-item

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/iron-menu-behavior#13]
How do I listen/capture to change in "focusedItem" of iron-menu-behaviour? I cannot see any event or property change listener for an item change i.e. change in paper-item selection within a paper-menu.

**Comment by ericguzman** [comment]
I'm having trouble with this, as well. Not sure if one-way, upward binding to "focusedItem" is supposed to work here, but I haven't had any success.

As an aside, the documentation (here: https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#property-notification) implies that "notify: true" should be set for upward binding. A closed issue stated that this isn't true -- perhaps the docs can updated to prevent confusion.

**Comment by morethanreal** [comment]
`notify:true` is required for binding a property value upwards, but currently that is not supported for `focusedItem`. Note that selection state and focus state is not equivalent.

**Comment by Trakkasure** [comment]
If you notice, paper-menu implements this behavior, which also implements the Polymer.IronMultiSelectableBehavior. I am unsure why multi-select for menus. Use you can watch selectedValues if multi is enabled or selectedValue, or listen to the iron-select event. There is a patch for multi-select behavior. I suggest using the patch if you are using multi-select.

**Comment by cdata** [comment]
Hi, is there a bug report or feature request here? If so, please re-open with a more specific request. Thanks!
