### ISSUE TITLE
would expect spacebar or enter to have function on an accessible menu

### ISSUE THREAD

**Issue by ktiedt** [PolymerElements/iron-menu-behavior#14]
Generally one would expect spacebar or enter to select items in an accessible menu. At least in the demo, this does nothing.

**Comment by morethanreal** [comment]
Same cause as https://github.com/PolymerElements/paper-tabs/issues/28

**Comment by shawncplus** [comment]
This can be fixed directly in iron-menu-behavior by forcing https://github.com/PolymerElements/iron-menu-behavior/blob/master/iron-menu-behavior.html#L158

to read

```
this._activateFocused({ type: 'tap', target: event.detail.keyboardEvent.target});
```

It's a temporary and very fragile fix but it works

**Comment by cdata** [comment]
Hi, I believe that this has been fixed by https://github.com/PolymerElements/iron-menu-behavior/pull/25 and https://github.com/PolymerElements/paper-item/pull/27. Please re-open if you think there is still a problem!
