### ISSUE TITLE
core-submenu alternative?

### ISSUE THREAD

**Issue by ktiedt** [PolymerElements/iron-menu-behavior#16]
https://github.com/Polymer/core-menu links to here as the 1.0 alternative to core-menu/submenu, but I do not see any submenu like features in iron or paper elements...

Was this overlooked, or is the proper approach to compose your own solution with iron-collapse wrapped items?

**Comment by ktiedt** [comment]
I see that submenu was added to the polymer README file after I looked last, so I suppose this is technically a resolved thing, unless someone wants to propose an alternative in the mean time.

**Comment by jenyckee** [comment]
So what element supports sub-menu now?

**Comment by ktiedt** [comment]
Sorry, I should have linked to the page I referenced: submenu is still "planned" but not in progress, in theory it should be available before Sep 21st unless the deadline gets pushed again....

https://github.com/PolymerElements/paper-elements

**Comment by glaucomunsberg** [comment]
Guys the paper-submenu was done and submit 😉 U need update your paper-menu to last version https://github.com/PolymerElements/paper-menu/blob/master/paper-submenu.html
