### ISSUE TITLE
Make it possible to have decorative items in the menu

### ISSUE THREAD

**Issue by kirilledelman** [PolymerElements/iron-menu-behavior#17]
I have a need to have non-item elements in the menu ( it's a drop-down menu, and it has a couple sections that need to be separated ). I've added `<hr/>` as a separator element, but it remains keyboard-accessible, and receives focus when using up / down keys to navigate the menu.

I suspect you're going to tell me to use CSS to add separators, but let me say that 1) others are going to continue to put non-menu items in the menu and expect it to work, and 2) there's a simple-ish workaround for this: just make the keyboard navigation skip items that have `disabled` attribute. There's no point to allow focusing on them with keyboard anyway, as you can now.

This will allow any decorative items in the menu, without breaking the functionality, just by adding `disabled` attribute.

**Comment by filipproch** [comment]
yeah, i would also appreciate this, I would like to have the ability to add some "not selectable" attribute to menu item, which would no longer be considered as menu item, I want to use this for category headlines (i have menu items split into several categories) and I really don't want to have these category names selectable

**Comment by bicknellr** [comment]
It's a bit hidden, but the `selectable` property ([inherited from IronSelectableBehavior](https://github.com/PolymerElements/iron-selector/blob/f97d342dd2e0b8b6b25230b024fff5b3903b0a4a/iron-selectable.html#L91)) should make this pretty simple.
