### ISSUE TITLE
Should "multi" be documented as a property?

### ISSUE THREAD

**Issue by arthurevans** [PolymerElements/iron-menu-behavior#18]
It appears that we treat `multi` as a property, but don't have an entry for it in the `properties` object or any doc for it.

**Comment by notwaldorf** [comment]
`multi` comes from `Polymer.IronMultiSelectableBehavior`: https://github.com/PolymerElements/iron-selector/blob/master/iron-multi-selectable.html#L22

**Comment by arthurevans** [comment]
D'ooooh. We need to inline the behavior docs. So. Badly.

**Comment by notwaldorf** [comment]
:100: agree
