### ISSUE TITLE
Selecting items breaks tabindex

### ISSUE THREAD

**Issue by robdodson** [PolymerElements/iron-menu-behavior#19]
You can see the error on this page: https://polymer-todo.firebaseapp.com

Tab through the menu and click on the last item. It will add `tabindex=-1` to the first menu item. Now you can't shift-tab back to that item.

**Comment by cdata** [comment]
I think this may have been fixed by #25 . Could you verify that there is still a problem, and then re-open if it can be reproduced? Thanks!
