### ISSUE TITLE
Docs: this behavior is missing docs

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/iron-menu-behavior#20]
As a result, paper-tabs and others have a lot of functionality missing.

@cdata @blasten @tjsavage how do we get this in the catalog?

**Comment by garlicnation** [comment]
Fixed, will mark closed when catalog is updated.

**Comment by garlicnation** [comment]
https://elements.polymer-project.org/elements/iron-menu-behavior?active=Polymer.IronMenuBehavior
