### ISSUE TITLE
_resetTabindices should have a public proxy method exposed

### ISSUE THREAD

**Issue by samccone** [PolymerElements/iron-menu-behavior#26]
**Why**

Currently if you have a dynamic set of menu items and want to have them have this menu behavior the only way to rebind to the new nodes is by calling this private method :finnadie: 

Real world :earth_asia: example :cyclone: 

https://github.com/samccone/paper-typeahead/blob/master/paper-typeahead-results.html#L49

Thanks for your time :clap:

**Comment by cdata** [comment]
Thanks for reporting! Now that we have `Polymer.dom(...).observeNodes`,  we should be able to rebind automatically based on items changing.

**Comment by bicknellr** [comment]
@cdata Was this fixed [here](https://github.com/PolymerElements/iron-selector/commit/0546fb37e5969bf25df6655caaefb8057b0cc0c7)?

**Comment by cdata** [comment]
Yes, I think this has been fixed. Please re-open if not!
