### ISSUE TITLE
Documentation mismatch in v1.0.5: attrForSelected

### ISSUE THREAD

**Issue by johanmynhardt** [PolymerElements/iron-menu-behavior#32]
Hi :)

I'm not 100% sure that I found an issue, but I've tried to find the documentation in a freshly cloned repository on the property `attrForSelected` which features on https://elements.polymer-project.org/elements/iron-menu-behavior (at time of writing at v1.0.5).

However, it does not appear in the cloned repo code.
I'm very new to Polymer so I am not sure whether I missed something when trying to find it.

**Comment by cdata** [comment]
Hi, `attrForSelected` is documented where it is implemented (https://github.com/PolymerElements/iron-selector). We are working to update our docs to surface transitive / inherited implementation. I'm gonna close this issue for now.
