### ISSUE TITLE
feature request: 'change' event

### ISSUE THREAD

**Issue by mgiuffrida** [PolymerElements/iron-menu-behavior#37]
It would be useful to know when the user selects an item from the menu, instead of the selected property changing via data binding.

`IronButtonState` fires a `change` event when the state changes due to user interaction. This is useful for handling changes made by the user, as `iron-change` may get fired when the state changes due to data binding.

How hard would it be to add `change` to IronMenuBehavior?

**Comment by notwaldorf** [comment]
@mgiuffrida `IronMenuBehavior` implements the `IronMultiSelectableBehavior`, which implements `IronSelectableBehavior` (I admit this takes a bit of detective work), which fires a whole bunch of events: https://github.com/PolymerElements/iron-selector/blob/master/iron-selectable.html#L19. I think you probably want `iron-activate`

Edit: Oops, found out that the latest version of the catalog actually shows all of the events, so the detective work wasn't needed: https://elements.polymer-project.org/elements/iron-menu-behavior

**Comment by mgiuffrida** [comment]
I'm aware of those events but they're not inherently useful for detecting a user change (i.e., the same actions that would trigger the `change` event in a `<select>`).

when clicking an item that isn't selected,  `iron-activate` fires _before_ the `selected` property changes.

when clicking at item that is already selected, `iron-activate` fires even though `iron-select` doesn't fire.

so to (imperfectly) detect that a user tapping an item is what triggered the change in `selected`, you'd have to do something like:
1. when `iron-activate` fires: `this.lastActivation_ =  new Date();`
2. when `iron-selected` fires: assume a user action caused the selection change if `new Date() - this.lastActivation_ < EPSILON`, and reset `this.lastActivation_ = 0` for next time

**Comment by bicknellr** [comment]
@mgiuffrida [The `iron-activate` event comes with the selected item and value](https://github.com/PolymerElements/iron-selector/blob/f97d342dd2e0b8b6b25230b024fff5b3903b0a4a/iron-selectable.html#L318), you should be able to check against the currently selected item / value to know if `selected` will change as a result of a user action. Would this work for you?

(+@notwaldorf) Thoughts about adding a separate `change` event for this case?

**Comment by mgiuffrida** [comment]
@bicknellr `iron-activate` does not get called if the selected radio button is changed using the arrow keys.

[Here is a fiddle showing my problem.](http://jsfiddle.net/025cfn0x/)

The goal is just to detect when the user changes the radio group, and ignore cases when |selected| is changed by pressing the <button> (simulating, say, an ajax response). I can't figure out a nice way to do that but it seems like a simple goal (again, HTML already has this).

**Comment by bicknellr** [comment]
I think this is a problem with with paper-radio-group, it skips calling [`_itemActivate`](https://github.com/PolymerElements/iron-selector/blob/f97d342dd2e0b8b6b25230b024fff5b3903b0a4a/iron-selectable.html#L316) and instead calls select directly from its keyboard handlers even though they activate the item as well. [PR here.](https://github.com/PolymerElements/paper-radio-group/pull/49)
