### ISSUE TITLE
focusedItem needs notify: true

### ISSUE THREAD

**Issue by michaelpg** [PolymerElements/iron-menu-behavior#4]
the property is readOnly: true and notify: false, which by Polymer's own documentation is "nonsensical".

We would appreciate a fix for 0.8 as well, and a release tag for the change.

**Comment by morethanreal** [comment]
Why is `readOnly:true` and `notify:false` a nonsensical state? `notify:false` just means other elements cannot be notified of changes to `focusedItem`. Can you describe a use case where you need to be notified of `focusedItem` changing?

**Comment by michaelpg** [comment]
I'm not sure what I was thinking now :-\

I was having a problem with paper-menu but I'm not having that issue now, and I don't remember the specifics of how I thought I traced it to this property. I agree `readOnly: true` and `notify: false` is fine; I must have misread the documentation that day. Sorry!
