### ISSUE TITLE
new event fired ?

### ISSUE THREAD

**Issue by ghost** [PolymerElements/iron-menu-behavior#40]
Hi there,

I've just updated polymer & components.
Since the update, there is something new.

I have a <paper-dialog> element.
Inside this element, I have a <paper-menu> with multiple <paper-item> on the left, and a simple <div> on the right.

Before the update, when clicking on a <paper-item> element, some actions were done, like change the content of the <div> element.
It appears that, since the update, when clicking a <paper-item> an event "iron-overlay-closed" is broadcasted, which close the dialog when clicking on the menu.
If I comment the content of the function _activateHandler (iron-menu-behaviors.html:304 the event is no longer forwarded?

Is it normal that this event is broadcasted?
Thanks

**Comment by bicknellr** [comment]
Are you seeing this event fired when there's not an overlay being closed?

**Comment by ghost** [comment]
I'll confirm this ASAP this morning.
In fact, after searching a little bit more about this problem I'm not sure that the event is broadcasted when clicking, I think he's just forwarded because of the dialog closing.
I'll find more informations, and come back asap.

**Comment by ghost** [comment]
That's it.
The iron-overlay-closed is only fired because of dialog closing.

UPDATE : when removing <paper-menu> and using only <paper-item> the dialog won't close anymore when selecting an item
UPDATE 2 : if I remove the tap event of the <paper-menu> the problem will no longer appear (it does not reach the _activateHandler function, that's why)

**Comment by ghost** [comment]
FYI : https://jsbin.com/jufuxotawu/edit?html,console,output

**Comment by MeTaNoV** [comment]
Same here: https://jsbin.com/jufuxotawu/edit?html,console,output

**Comment by GeoloeG-IsT** [comment]
Here you are! :)

**Comment by bicknellr** [comment]
After some investigating, it looks like `iron-menu-behavior` is capturing events that `iron-overlay-behavior` listens for to determine if it should close. [Here's the `iron-overlay-behavior` PR.](https://github.com/PolymerElements/iron-overlay-behavior/pull/64)

**Comment by GeoloeG-IsT** [comment]
@bicknellr Link is broken like iron-overlay-behavior is! :)

**Comment by bicknellr** [comment]
Fixed; it's the one right above the comment in the timeline anyways.

(edit: By 'fixed' i was referring to the link in my previous comment, not this issue.)

**Comment by GeoloeG-IsT** [comment]
kidding, need to check master if the last development on it resolve the problem I have with multiple dialog, else I will Issue, but it will be a tricky one...

**Comment by ghost** [comment]
Up, I've updated the linked issue by @bicknellr 
It seems that the problem is always here when using paper-dropdown-menu inside a dialog

https://jsbin.com/lapedorogo/edit?html,console,output

Should I open a new issue?

**Comment by ghost** [comment]
Update : no need to select an item, clicking outside to hide the list will have the same effect

**Comment by bicknellr** [comment]
(@bastienarm has opened PolymerElements/iron-overlay-behavior#70)
