### ISSUE TITLE
Don't blur if you're going to immediately set focus after

### ISSUE THREAD

**Issue by robdodson** [PolymerElements/iron-menu-behavior#50]
This line seems unnecessary https://github.com/PolymerElements/iron-menu-behavior/blob/b797c3501bdc9085810e0d5557bc8af084a64564/iron-menu-behavior.html#L249 and is creating a keyboard trap if you have paper-tabs on the page without a paper-tab inside of it.

**Comment by bicknellr** [comment]
Yeah, it really doesn't make sense to call blur there.
